// Dados sincronizados do blog em Português (Total: 54 artigos)
const BLOG_POSTS = [
  {
    "id": "4-metros-para-pes",
    "slug": "/pt/blog/4-metros-para-pes",
    "title": "4 Metros para Pés",
    "date": "2026-10-08",
    "publicationDate": "2026-10-08T00:13:04.362Z",
    "category": "Comprimento e Distância",
    "categoryKey": "Length & Distance",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "📏",
    "image": "https://images.unsplash.com/photo-1606120312321-d65083a14576?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8NCUyMG1ldGVycyUyMHRvJTIwZmVldHxlbnwwfHx8fDE3OTE0MTgzMzN8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Converta 4 metros para pés com precisão usando fórmulas matemáticas, atalhos de cálculo mental, tabelas de conversão e calculadora online.",
    "order": 0
  },
  {
    "id": "2000-usd-to-gbp",
    "slug": "/pt/blog/2000-usd-to-gbp",
    "title": "2000 USD para GBP (Dólar para Libra)",
    "date": "2026-10-07",
    "publicationDate": "2026-10-07T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1517232117795-40c9d8212a04?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8NXx8MjAwMCUyMHVzZCUyMHRvJTIwZ2JwfGVufDB8fHx8MTc5MTMzMjAwNXww&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Converta 2000 USD para GBP com precisão usando fórmulas matemáticas passo a passo, atalhos mentais, tabelas e conversor ao vivo.",
    "order": 1
  },
  {
    "id": "1500-usd-para-gbp",
    "slug": "/pt/blog/1500-usd-para-gbp",
    "title": "1500 USD para GBP",
    "date": "2026-10-06",
    "publicationDate": "2026-10-06T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=1200&q=80",
    "summary": "Converta 1500 USD para GBP com precisão usando fórmulas matemáticas passo a passo, atalhos de cálculo mental, tabelas e calculadora ao vivo.",
    "order": 2
  },
  {
    "id": "95-usd-para-gbp",
    "slug": "/pt/blog/95-usd-para-gbp",
    "title": "95 Usd para Gbp",
    "date": "2026-10-05",
    "publicationDate": "2026-10-05T12:07:34Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
    "summary": "Converta 95 usd para gbp com precisão usando fórmulas passo a passo, atalhos de cálculo mental, tabelas e conversor ao vivo.",
    "order": 3
  },
  {
    "id": "1500-usd-para-aud",
    "slug": "/pt/blog/1500-usd-para-aud",
    "title": "1500 Dólares USD para AUD: Fórmula e Conversor",
    "date": "2026-10-05",
    "publicationDate": "2026-10-05T00:16:47Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1670071479248-cc25dfd919a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8MTUwMCUyMHVzZCUyMHRvJTIwYXVkfGVufDB8fHx8MTc5MTE1OTE2OXww&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 1500 Dólares USD para AUD. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 4
  },
  {
    "id": "65-kg-para-libras",
    "slug": "/pt/blog/65-kg-para-libras",
    "title": "65 Quilos para Libras: Fórmula e Conversor",
    "date": "2026-10-04",
    "publicationDate": "2026-10-04T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1664352603314-6047584b3e10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8M3x8NjUlMjBrZyUyMHBvdW5kc3xlbnwwfHx8fDE3OTEwODMxNzd8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 65 Quilos para Libras. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 5
  },
  {
    "id": "165-libras-para-kg",
    "slug": "/pt/blog/165-libras-para-kg",
    "title": "165 Libras para Quilos: Fórmula e Conversor",
    "date": "2026-10-03",
    "publicationDate": "2026-10-03T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1689514226761-336eaf77e311?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8Mnx8MTY1JTIwbGJzJTIwdG8lMjBrZ3xlbnwwfHx8fDE3OTA5ODYzMTJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 165 Libras para Quilos. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 6
  },
  {
    "id": "14-stone-em-libras",
    "slug": "/pt/blog/14-stone-em-libras",
    "title": "14 Stone em Libras (lbs): Fórmula e Conversor",
    "date": "2026-10-02",
    "publicationDate": "2026-10-02T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1592899436433-8abe4656570c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8MTQlMjBzdG9uZSUyMGluJTIwcG91bmRzfGVufDB8fHx8MTc5MDg5OTk0M3ww&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 14 Stone em Libras (lbs). Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 7
  },
  {
    "id": "15-metros-para-pes",
    "slug": "/pt/blog/15-metros-para-pes",
    "title": "15 Metros para Pés: Fórmula e Conversor",
    "date": "2026-10-01",
    "publicationDate": "2026-10-01T00:00:00Z",
    "category": "Comprimento e Distância",
    "categoryKey": "Length & Distance",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "📏",
    "image": "https://images.unsplash.com/photo-1600518386631-1deefa2dc398?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8MTUlMjBtZXRlcnMlMjB0byUyMGZlZXR8ZW58MHx8fHwxNzkwODQxMjY4fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 15 Metros para Pés. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 8
  },
  {
    "id": "16-oncas-para-mililitros",
    "slug": "/pt/blog/16-oncas-para-mililitros",
    "title": "16 Onças Fluidas para Mililitros: Fórmula e Conversor",
    "date": "2026-10-01",
    "publicationDate": "2026-10-01T00:00:00Z",
    "category": "Volume & Geometria",
    "categoryKey": "Volume & Geometry",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "🧪",
    "image": "https://images.unsplash.com/photo-1523621509625-54893aa665ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8MTYlMjBvdW5jZXMlMjB0byUyMG1pbGxpbGl0ZXJzfGVufDB8fHx8MTc5MDgxMzU3Mnww&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 16 Onças Fluidas para Mililitros. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 9
  },
  {
    "id": "180-libras-em-stone",
    "slug": "/pt/blog/180-libras-em-stone",
    "title": "180 Libras em Stone: Fórmula e Conversor",
    "date": "2026-09-30",
    "publicationDate": "2026-09-30T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1629878734837-9506604e605a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8MTgwbGJzJTIwaW4lMjBzdG9uZXxlbnwwfHx8fDE3OTA3MjcxMzZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 180 Libras em Stone. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 10
  },
  {
    "id": "converter-lakh-para-usd",
    "slug": "/pt/blog/converter-lakh-para-usd",
    "title": "Converter Lakh para USD: Fórmula e Conversor",
    "date": "2026-09-29",
    "publicationDate": "2026-09-29T00:00:00Z",
    "category": "Unidades Indianas e Terras",
    "categoryKey": "Indian Units & Land",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "🇮🇳",
    "image": "https://images.unsplash.com/photo-1593672715438-d88a70629abe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8Y29udmVydCUyMGxha2glMjB0byUyMHVzZHxlbnwwfHx8fDE3OTA2NDA3Nzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para Converter Lakh para USD. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 11
  },
  {
    "id": "5-usd-para-aud",
    "slug": "/pt/blog/5-usd-para-aud",
    "title": "5 Dólares USD para AUD: Fórmula e Conversor",
    "date": "2026-09-28",
    "publicationDate": "2026-09-28T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1580519542036-c47de6196ba5?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 5 Dólares USD para AUD. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 12
  },
  {
    "id": "3-xicaras-em-ml",
    "slug": "/pt/blog/3-xicaras-em-ml",
    "title": "3 Xícaras em Mililitros: Fórmula e Conversor",
    "date": "2026-09-27",
    "publicationDate": "2026-09-27T00:00:00Z",
    "category": "Culinária & Cozinha",
    "categoryKey": "Kitchen & Culinary",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "🍳",
    "image": "https://images.unsplash.com/photo-1570784331625-907b0c979f63?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8MyUyMGN1cHMlMjBpbiUyMG1sfGVufDB8fHx8MTc5MDUxMjc4OHww&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 3 Xícaras em Mililitros. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 13
  },
  {
    "id": "moeda-jpy-para-inr",
    "slug": "/pt/blog/moeda-jpy-para-inr",
    "title": "Iene Japonês para Rúpia Indiana (JPY para INR): Fórmula e...",
    "date": "2026-09-24",
    "publicationDate": "2026-09-24T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para Iene Japonês para Rúpia Indiana (JPY para INR). Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 14
  },
  {
    "id": "moeda-lira-turca",
    "slug": "/pt/blog/moeda-lira-turca",
    "title": "Moeda Lira Turca (TRY): Fórmula e Conversor",
    "date": "2026-09-24",
    "publicationDate": "2026-09-24T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1579807102908-396b3b737800?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8Y3VycmVuY3klMjBmb3IlMjB0dXJraXNoJTIwbGlyYXxlbnwwfHx8fDE3OTAyMDkwNDV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para Moeda Lira Turca (TRY). Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 15
  },
  {
    "id": "convertor-ou-converter",
    "slug": "/pt/blog/convertor-ou-converter",
    "title": "Convertor ou Converter? Grafia Correta: Fórmula e Conversor",
    "date": "2026-09-23",
    "publicationDate": "2026-09-23T00:00:00Z",
    "category": "Guias de Conversão",
    "categoryKey": "Conversion Guide",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "📊",
    "image": "https://images.unsplash.com/photo-1595428316411-9e9669619c4a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8Y29udmVydG9yJTIwb3IlMjBjb252ZXJ0ZXJ8ZW58MHx8fHwxNzkwMTIyNDUwfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para Convertor ou Converter? Grafia Correta. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 16
  },
  {
    "id": "12-graus-celsius-para-fahrenheit",
    "slug": "/pt/blog/12-graus-celsius-para-fahrenheit",
    "title": "12 Graus Celsius para Fahrenheit: Fórmula e Conversor",
    "date": "2026-09-22",
    "publicationDate": "2026-09-22T00:00:00Z",
    "category": "Temperatura & Culinária",
    "categoryKey": "Temperature & Cooking",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "🌡️",
    "image": "https://images.unsplash.com/photo-1740560516658-5a94b0b715ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8MTIlMjBkZWdyZWVzJTIwY2Vsc2l1cyUyMHRvJTIwZmFocmVuaGVpdHxlbnwwfHx8fDE3OTAwNTc2NDV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 12 Graus Celsius para Fahrenheit. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 17
  },
  {
    "id": "170-libras-em-stone",
    "slug": "/pt/blog/170-libras-em-stone",
    "title": "170 Libras em Stone: Fórmula e Conversor",
    "date": "2026-09-22",
    "publicationDate": "2026-09-22T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1709247389603-ba5c59e86199?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8MTcwbGJzJTIwaW4lMjBzdG9uZXxlbnwwfHx8fDE3OTAwNzkyMjN8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 170 Libras em Stone. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 18
  },
  {
    "id": "20-libras-em-dolares-australianos",
    "slug": "/pt/blog/20-libras-em-dolares-australianos",
    "title": "20 Libras Esterlinas em Dólares Australianos (AUD): Fórmu...",
    "date": "2026-09-22",
    "publicationDate": "2026-09-22T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1518458028785-8fbcd101ebb9?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 20 Libras Esterlinas em Dólares Australianos (AUD). Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 19
  },
  {
    "id": "199-usd-em-aud",
    "slug": "/pt/blog/199-usd-em-aud",
    "title": "199 Dólares USD em AUD: Fórmula e Conversor",
    "date": "2026-09-21",
    "publicationDate": "2026-09-21T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1593672755342-741a7f868732?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8MTk5JTIwdXNkJTIwaW4lMjBhdWR8ZW58MHx8fHwxNzg5OTkyNzc4fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 199 Dólares USD em AUD. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 20
  },
  {
    "id": "2000-dolares-em-libras",
    "slug": "/pt/blog/2000-dolares-em-libras",
    "title": "2000 Dólares em Libras Esterlinas (GBP): Fórmula e Conversor",
    "date": "2026-09-21",
    "publicationDate": "2026-09-21T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1607166602071-847b7d110781?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8MjAwMCUyMGRvbGxhcnMlMjBpbiUyMHBvdW5kc3xlbnwwfHx8fDE3OTAwMTQzNDR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 2000 Dólares em Libras Esterlinas (GBP). Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 21
  },
  {
    "id": "80-quilos-para-libras",
    "slug": "/pt/blog/80-quilos-para-libras",
    "title": "80 Quilos para Libras: Fórmula e Conversor",
    "date": "2026-09-21",
    "publicationDate": "2026-09-21T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1522844990619-4951c40f7eda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8ODAlMjBraWxvJTIwbGJzfGVufDB8fHx8MTc4OTk0OTcwMHww&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 80 Quilos para Libras. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 22
  },
  {
    "id": "taxa-de-cambio-mastercard",
    "slug": "/pt/blog/taxa-de-cambio-mastercard",
    "title": "Taxas de Câmbio e Tarifas Mastercard: Fórmula e Conversor",
    "date": "2026-09-21",
    "publicationDate": "2026-09-21T00:00:00Z",
    "category": "Guias de Conversão",
    "categoryKey": "Conversion Guide",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "📊",
    "image": "https://images.unsplash.com/photo-1589758438368-0ad531db3366?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8bWFzdGVyY2FyZCUyMGZvcmVpZ24lMjBleGNoYW5nZSUyMHJhdGV8ZW58MHx8fHwxNzg5OTcxMzE3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para Taxas de Câmbio e Tarifas Mastercard. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 23
  },
  {
    "id": "10-bilhoes-de-won-para-gbp",
    "slug": "/pt/blog/10-bilhoes-de-won-para-gbp",
    "title": "10 Bilhões de Won para Libras (GBP): Fórmula e Conversor",
    "date": "2026-09-20",
    "publicationDate": "2026-09-20T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1703319953489-996cf05b6958?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8MTAlMjBiaWxsaW9uJTIwd29uJTIwdG8lMjBnYnB8ZW58MHx8fHwxNzg5ODg0NzkwfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 10 Bilhões de Won para Libras (GBP). Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 24
  },
  {
    "id": "32-usd-para-gbp",
    "slug": "/pt/blog/32-usd-para-gbp",
    "title": "32 Dólares USD para Libras (GBP): Fórmula e Conversor",
    "date": "2026-09-20",
    "publicationDate": "2026-09-20T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1703437874457-560d410f82fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8Mnx8MzIlMjB1c2QlMjB0byUyMGdicHxlbnwwfHx8fDE3ODk5Mjc5MDZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 32 Dólares USD para Libras (GBP). Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 25
  },
  {
    "id": "calculadora-de-semanas",
    "slug": "/pt/blog/calculadora-de-semanas",
    "title": "Calculadora de Semanas e Dias: Fórmula e Conversor",
    "date": "2026-09-20",
    "publicationDate": "2026-09-20T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1648201637025-1c77b9be3013?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8d2Vla3MlMjBjYWxjdWxhdG9yfGVufDB8fHx8MTc4OTkwNjM3MXww&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para Calculadora de Semanas e Dias. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 26
  },
  {
    "id": "converter-formulario-pdf",
    "slug": "/pt/blog/converter-formulario-pdf",
    "title": "Converter Formulário PDF: Fórmula e Conversor",
    "date": "2026-09-20",
    "publicationDate": "2026-09-20T00:00:00Z",
    "category": "Arquivos & Ferramentas",
    "categoryKey": "File & Media Tools",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "📁",
    "image": "https://images.unsplash.com/photo-1631651693480-97f1132e333d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8Y29udmVydCUyMHBkZiUyMGZvcm18ZW58MHx8fHwxNzg5OTAxMzE3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para Converter Formulário PDF. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 27
  },
  {
    "id": "converter-tipo-de-arquivo-para-pdf",
    "slug": "/pt/blog/converter-tipo-de-arquivo-para-pdf",
    "title": "Converter Tipo de Arquivo para PDF: Fórmula e Conversor",
    "date": "2026-09-20",
    "publicationDate": "2026-09-20T00:00:00Z",
    "category": "Arquivos & Ferramentas",
    "categoryKey": "File & Media Tools",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "📁",
    "image": "https://images.unsplash.com/photo-1596299786121-66852dfb4b61?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8Y29udmVydCUyMGZpbGUlMjB0eXBlJTIwdG8lMjBwZGZ8ZW58MHx8fHwxNzg5ODYzMzI0fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para Converter Tipo de Arquivo para PDF. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 28
  },
  {
    "id": "13-stone-em-libras",
    "slug": "/pt/blog/13-stone-em-libras",
    "title": "13 Stone em Libras (lbs): Fórmula e Conversor",
    "date": "2026-09-19",
    "publicationDate": "2026-09-19T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1646829873498-e874cfa27933?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8MTMlMjBzdG9uZSUyMGluJTIwcG91bmRzfGVufDB8fHx8MTc4OTg0MTQ5OXww&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 13 Stone em Libras (lbs). Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 29
  },
  {
    "id": "71-libras-para-kg",
    "slug": "/pt/blog/71-libras-para-kg",
    "title": "71 Libras para Quilos: Fórmula e Conversor",
    "date": "2026-09-19",
    "publicationDate": "2026-09-19T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1559724087-a45f6a7a35d7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8NzElMjBwb3VuZHMlMjB0byUyMGtnfGVufDB8fHx8MTc4OTc3Njg2N3ww&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 71 Libras para Quilos. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 30
  },
  {
    "id": "modificador-de-arquivos",
    "slug": "/pt/blog/modificador-de-arquivos",
    "title": "Modificador de Formato de Arquivos: Fórmula e Conversor",
    "date": "2026-09-19",
    "publicationDate": "2026-09-19T00:00:00Z",
    "category": "Arquivos & Ferramentas",
    "categoryKey": "File & Media Tools",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "📁",
    "image": "https://images.unsplash.com/photo-1569235186275-626cb53b83ce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8ZmlsZSUyMGNoYW5nZXJ8ZW58MHx8fHwxNzg5ODE5OTY2fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para Modificador de Formato de Arquivos. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 31
  },
  {
    "id": "rupia-para-aud",
    "slug": "/pt/blog/rupia-para-aud",
    "title": "Rúpia Indonésia para AUD: Fórmula e Conversor",
    "date": "2026-09-19",
    "publicationDate": "2026-09-19T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1619149808494-d9a0a7eba166?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8cnVwaWFoJTIwdG8lMjBhdWR8ZW58MHx8fHwxNzg5Nzk4Mzk1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para Rúpia Indonésia para AUD. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 32
  },
  {
    "id": "300-dolares-em-gbp",
    "slug": "/pt/blog/300-dolares-em-gbp",
    "title": "300 Dólares em Libras (GBP): Fórmula e Conversor",
    "date": "2026-09-18",
    "publicationDate": "2026-09-18T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1703925153970-0e2e3a899e66?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8Mnx8MzAwJTIwZG9sbGFycyUyMGluJTIwZ2JwfGVufDB8fHx8MTc4OTcxMzUyOHww&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 300 Dólares em Libras (GBP). Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 33
  },
  {
    "id": "baixar-aplicativo-conversor",
    "slug": "/pt/blog/baixar-aplicativo-conversor",
    "title": "Baixar Aplicativo de Conversão: Fórmula e Conversor",
    "date": "2026-09-18",
    "publicationDate": "2026-09-18T00:00:00Z",
    "category": "Guias de Conversão",
    "categoryKey": "Conversion Guide",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "📊",
    "image": "https://images.unsplash.com/photo-1663124178703-d2d6a333e6c2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8Y29udmVydGVyJTIwYXBwbGljYXRpb24lMjBkb3dubG9hZHxlbnwwfHx8fDE3ODk3NTUxMTV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para Baixar Aplicativo de Conversão. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 34
  },
  {
    "id": "guia-moeda-indonesia",
    "slug": "/pt/blog/guia-moeda-indonesia",
    "title": "Guia da Moeda da Indonésia (Rúpia IDR): Fórmula e Conversor",
    "date": "2026-09-18",
    "publicationDate": "2026-09-18T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1501179691627-eeaa65ea017c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8aW5kb25lc2lhJTIwY3V8ZW58MHx8fHwxNzg5NjkwNDc1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para Guia da Moeda da Indonésia (Rúpia IDR). Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 35
  },
  {
    "id": "won-sul-coreano-para-aud",
    "slug": "/pt/blog/won-sul-coreano-para-aud",
    "title": "Won Sul-Coreano para Dólares Australianos (AUD): Fórmula...",
    "date": "2026-09-18",
    "publicationDate": "2026-09-18T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para Won Sul-Coreano para Dólares Australianos (AUD). Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 36
  },
  {
    "id": "1-aud-para-vnd",
    "slug": "/pt/blog/1-aud-para-vnd",
    "title": "1 AUD para VND (Dólar Australiano para Dong Vietnamita):...",
    "date": "2026-09-17",
    "publicationDate": "2026-09-17T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1608731433809-149763562571?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8MSUyMGF1ZCUyMHRvJTIwdm5kfGVufDB8fHx8MTc4OTY0NzQ5Mnww&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para 1 AUD para VND (Dólar Australiano para Dong Vietnamita). Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 37
  },
  {
    "id": "1-bilhao-de-won-para-gbp",
    "slug": "/pt/blog/1-bilhao-de-won-para-gbp",
    "title": "1 Bilhão de Won para Libras (GBP): Fórmula e Conversor",
    "date": "2026-09-17",
    "publicationDate": "2026-09-17T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 1 Bilhão de Won para Libras (GBP). Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 38
  },
  {
    "id": "como-mudar-formato-de-arquivo",
    "slug": "/pt/blog/como-mudar-formato-de-arquivo",
    "title": "Como Mudar o Formato de um Arquivo: Fórmula e Conversor",
    "date": "2026-09-17",
    "publicationDate": "2026-09-17T00:00:00Z",
    "category": "Arquivos & Ferramentas",
    "categoryKey": "File & Media Tools",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "📁",
    "image": "https://images.unsplash.com/photo-1699275303864-67b6e1e11706?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDY4OTMyfDB8MXxzZWFyY2h8MXx8aG93JTIwdG8lMjBjaGFuZ2UlMjBmaWxlJTIwZm9ybWF0fGVufDB8fHx8MTc4OTY2ODc5OHww&ixlib=rb-4.1.0&q=80&w=1080",
    "summary": "Guia completo para Como Mudar o Formato de um Arquivo. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 39
  },
  {
    "id": "1-colher-de-cha-em-ml",
    "slug": "/pt/blog/1-colher-de-cha-em-ml",
    "title": "1 Colher de Chá em Mililitros: Fórmula e Conversor",
    "date": "2026-09-16",
    "publicationDate": "2026-09-16T00:00:00Z",
    "category": "Culinária & Cozinha",
    "categoryKey": "Kitchen & Culinary",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "🍳",
    "image": "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 1 Colher de Chá em Mililitros. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 40
  },
  {
    "id": "1-galao-em-litros",
    "slug": "/pt/blog/1-galao-em-litros",
    "title": "1 Galão em Litros: Fórmula e Conversor",
    "date": "2026-09-16",
    "publicationDate": "2026-09-16T00:00:00Z",
    "category": "Volume & Geometria",
    "categoryKey": "Volume & Geometry",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "🧪",
    "image": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 1 Galão em Litros. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 41
  },
  {
    "id": "1-stone-em-kg",
    "slug": "/pt/blog/1-stone-em-kg",
    "title": "1 Stone em Quilos: Fórmula e Conversor",
    "date": "2026-09-16",
    "publicationDate": "2026-09-16T00:00:00Z",
    "category": "Peso & Massa",
    "categoryKey": "Weight & Mass",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "⚖️",
    "image": "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 1 Stone em Quilos. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 42
  },
  {
    "id": "10-celsius-para-fahrenheit",
    "slug": "/pt/blog/10-celsius-para-fahrenheit",
    "title": "10 Graus Celsius para Fahrenheit: Fórmula e Conversor",
    "date": "2026-09-16",
    "publicationDate": "2026-09-16T00:00:00Z",
    "category": "Temperatura & Culinária",
    "categoryKey": "Temperature & Cooking",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "🌡️",
    "image": "https://images.unsplash.com/photo-1516431883659-655d41c09bf9?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 10 Graus Celsius para Fahrenheit. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 43
  },
  {
    "id": "100-kg-para-libras",
    "slug": "/pt/blog/100-kg-para-libras",
    "title": "100 Quilos para Libras (lbs): Fórmula e Conversor",
    "date": "2026-09-16",
    "publicationDate": "2026-09-16T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 100 Quilos para Libras (lbs). Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 44
  },
  {
    "id": "50-fahrenheit-para-celsius",
    "slug": "/pt/blog/50-fahrenheit-para-celsius",
    "title": "50 Graus Fahrenheit para Celsius: Fórmula e Conversor",
    "date": "2026-09-16",
    "publicationDate": "2026-09-16T00:00:00Z",
    "category": "Temperatura & Culinária",
    "categoryKey": "Temperature & Cooking",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "🌡️",
    "image": "https://images.unsplash.com/photo-1534088568595-a066f410bcda?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 50 Graus Fahrenheit para Celsius. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 45
  },
  {
    "id": "500-ml-para-xicaras",
    "slug": "/pt/blog/500-ml-para-xicaras",
    "title": "500 Mililitros para Xícaras: Fórmula e Conversor",
    "date": "2026-09-16",
    "publicationDate": "2026-09-16T00:00:00Z",
    "category": "Culinária & Cozinha",
    "categoryKey": "Kitchen & Culinary",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "🍳",
    "image": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 500 Mililitros para Xícaras. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 46
  },
  {
    "id": "60-mph-para-kmh",
    "slug": "/pt/blog/60-mph-para-kmh",
    "title": "60 MPH para KM/H: Fórmula e Conversor",
    "date": "2026-09-16",
    "publicationDate": "2026-09-16T00:00:00Z",
    "category": "Tecnologia & Dados",
    "categoryKey": "Product & Tech",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "⚡",
    "image": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 60 MPH para KM/H. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 47
  },
  {
    "id": "1-3-xicara-em-gramas",
    "slug": "/pt/blog/1-3-xicara-em-gramas",
    "title": "1/3 de Xícara em Gramas: Fórmula e Conversor",
    "date": "2026-09-15",
    "publicationDate": "2026-09-15T00:00:00Z",
    "category": "Culinária & Cozinha",
    "categoryKey": "Kitchen & Culinary",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "🍳",
    "image": "https://images.unsplash.com/photo-1588467850695-a898367ce465?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 1/3 de Xícara em Gramas. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 48
  },
  {
    "id": "1-4-xicara-em-ml",
    "slug": "/pt/blog/1-4-xicara-em-ml",
    "title": "1/4 de Xícara em Mililitros: Fórmula e Conversor",
    "date": "2026-09-15",
    "publicationDate": "2026-09-15T00:00:00Z",
    "category": "Culinária & Cozinha",
    "categoryKey": "Kitchen & Culinary",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "🍳",
    "image": "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 1/4 de Xícara em Mililitros. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 49
  },
  {
    "id": "1-bar-para-psi",
    "slug": "/pt/blog/1-bar-para-psi",
    "title": "1 Bar para PSI (Conversão de Pressão): Fórmula e Conversor",
    "date": "2026-09-15",
    "publicationDate": "2026-09-15T00:00:00Z",
    "category": "Volume & Geometria",
    "categoryKey": "Volume & Geometry",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "🧪",
    "image": "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 1 Bar para PSI (Conversão de Pressão). Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 50
  },
  {
    "id": "1-xicara-de-leite-em-ml",
    "slug": "/pt/blog/1-xicara-de-leite-em-ml",
    "title": "1 Xícara de Leite em Mililitros: Fórmula e Conversor",
    "date": "2026-09-15",
    "publicationDate": "2026-09-15T00:00:00Z",
    "category": "Culinária & Cozinha",
    "categoryKey": "Kitchen & Culinary",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "🍳",
    "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 1 Xícara de Leite em Mililitros. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 51
  },
  {
    "id": "100-fahrenheit-para-celsius",
    "slug": "/pt/blog/100-fahrenheit-para-celsius",
    "title": "100 Graus Fahrenheit para Celsius: Fórmula e Conversor",
    "date": "2026-09-15",
    "publicationDate": "2026-09-15T00:00:00Z",
    "category": "Temperatura & Culinária",
    "categoryKey": "Temperature & Cooking",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "🌡️",
    "image": "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 100 Graus Fahrenheit para Celsius. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 52
  },
  {
    "id": "100-usd-para-aud",
    "slug": "/pt/blog/100-usd-para-aud",
    "title": "100 Dólares USD para AUD: Fórmula e Conversor",
    "date": "2026-09-15",
    "publicationDate": "2026-09-15T00:00:00Z",
    "category": "Moedas & Câmbio",
    "categoryKey": "Currency & Forex",
    "author": "Equipe Editorial OmniConverter",
    "readTime": "4 min de leitura",
    "icon": "💱",
    "image": "https://images.unsplash.com/photo-1580519542036-c47de6196ba5?auto=format&fit=crop&w=1200&q=80",
    "summary": "Guia completo para 100 Dólares USD para AUD. Fórmulas matemáticas certificadas, tabelas de referência e conversor online.",
    "order": 53
  }
];

window.BLOG_POSTS = BLOG_POSTS;
window.blogArticles = BLOG_POSTS;
